version: '2'
services:

  # The Application
  app:
    build:
      context: ./.docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "PHP_IDE_CONFIG=serverName=dock"

  # The Web Server
  web:
    build:
      context: ./.docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8484:80

  # The Database
  database:
    image: mysql:5.7

    environment:
      MYSQL_DATABASE: page
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
    ports:
      - "33061:3306"

volumes:
  dbdata: